language: node_js
node_js:
  - stable
before_install:
  - export TZ=Europe/Oslo
install:
  - npm install
before_script:
  - npm run build

before_deploy:
  - git config --global user.email "abjolseth@gmail.com"
  - git config --global user.name "navikt"

deploy:
  provider: npm
  email: abjolseth@gmail.com
  api_key:
    secure: 54046c1c-fd9f-4a45-b08b-0b5f001bbfa6
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: navikt/melosys-kodeverk
