language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
before_install:
  - export TZ=Europe/Oslo
install:
  - npm install
script:
  - npm run test
  - npm run build
before_deploy:
  - git config --global user.email "abjolseth@gmail.com"
  - git config --global user.name "abjolseth"
deploy:
  provider: npm
  email: abjolseth@gmail.com
  api_key:
    secure: rnw2GdgO7KFIL6DYzyNh1SGV+l8eM4H2RNyP5mrumfDL9lW4kpx/J6/1/fugjCTleaUh6sHz0A/Hl/WLyD4DAEg3ggj/A2AFO7PTt9wLK3kWzCesh7xpAyf4MxkzLBCyjvDombXPdiIr1MLdrSQQnd1x0w5HZ+D1F7SogY04sHI/F40bGV2ytbAvnCV9iugzmC1BVWPRZ2cK7AwYlG0WCk3TAbWkbmdP6HN6xAraCEAS6WP7olvQBSQucjSA6wBUUHLYJ3SCXYFXwqOOf2xEWqPX7ROErd7U4o5dk39nev6b4j+Pzrmn04O8jaA+Wic6ovhcwGdMBbnMfpUXk/11zgjU1BKqW76xPamuuw5N3z0POJxIKNdm/RRLZOOi5x9kyZUMosuipszBOsXNe72VqUz0ptKW7ZDSQaXcOJOQN1AhJ1nGJ80Fpsx8/dkk2wd6a4k645Qgofo/5vT++agWDGientb0nAGuGCt9SLDacpsvvdVrMY8NPDQG2Rt2CbKzpCrajJXiD1lXHLPLTM5CTU4u7zaaEHZdTC3sORjkoteJ5YrHCpkbae3b8eLVhsUA8ZnKI6CF2naGsxz/BBcq7UwopFN+P/9N88v7IKT3L1ILtmy85KvVCpqo74D79qhKdraNwUqVTVYhp0brAouVVlzj/3nya5noNdYUFXAgnA4=
  on:
    tags: true
    repo: navikt/melosys-kodeverk
