on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  bygge_frontend:
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: v1-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            v1-yarn-
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - uses: actions/upload-artifact@v1
        with:
          name: melosys-kodeverk
          path: dist

  bygge_backend:
    needs: bygge_frontend
    runs-on: ubuntu-latest
    container: navikt/melosys-kodeverk-java:9e7b71c1691dfda48f4de4a55fd0b7d6e1b6a241
    steps:
      # GitHub Actions tillater kun filer under workspace i cache-nøkler
      - run: cp /app.jar .
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: v1-m2build-${{ hashFiles('app.jar') }}
          restore-keys: |
            v1-m2build-
      - uses: actions/download-artifact@v1
        with:
          name: melosys-kodeverk
          path: melosys-kodeverk-java/melosys-kodeverk/dist
      - name: Generere kildekode for Java-kodeverk
        working-directory: melosys-kodeverk-java
        run: |
          set -e
          java -jar ../app.jar melosys-kodeverk/dist/kodemap.yml
      - name: Bygge Java-kodeverk
        working-directory: melosys-kodeverk-java/melosys-internt-kodeverk
        run: mvn clean install -B -V
      - uses: actions/upload-artifact@v1
        with:
          name: melosys-kodeverk-java
          path: melosys-kodeverk-java

  tagge_frontend:
    if: github.ref == 'refs/heads/master'
    needs: bygge_backend
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          # FIXME: Dette er veldig, veldig grisete
          git config --global user.email "githubci-melosys@nav.no"
          git config --global user.name "GitHubCI"
          git remote set-url origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}"

          BRANCH=${GITHUB_REF#refs/heads/}
          git checkout -b ${BRANCH}
          git branch --set-upstream-to=origin/${BRANCH}

          echo "Tagger ny patch-versjon"

          GIT_COMMIT_DESC=$(git log --format=oneline -n 1 ${GITHUB_SHA})
          npm version patch -m "%s $GIT_COMMIT_DESC [skip ci]"
          git push && git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lag_snapshot_versjon:
    if: github.ref != 'refs/heads/master'
    needs: bygge_frontend
    runs-on: ubuntu-latest
    container: node:latest
    outputs:
      frontend_versjon: ${{ steps.versjoner.outputs.frontend }}
      backend_versjon: ${{ steps.versjoner.outputs.backend }}
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: melosys-kodeverk
          path: dist
      - id: versjoner
        run: |
          echo "::set-output name=frontend::$(cat dist/semver.txt)-beta.${PR_NUMBER}"
          echo "::set-output name=backend::$(cat dist/semver.txt)-SNAPSHOT"
        env:
          PR_NUMBER: ${{ github.event.number }}

  release_frontend_snapshot:
    needs: lag_snapshot_versjon
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          # TODO Sjekk om versjon kan gjenbrukes med beta-tag
          npm --no-git-tag-version version "${FRONTEND_VERSION}"
          npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FRONTEND_VERSION: ${{needs.lag_snapshot_versjon.outputs.frontend_versjon}}

  release_backend_snapshot:
    needs: [bygge_backend, lag_snapshot_versjon]
    runs-on: ubuntu-latest
    container: navikt/melosys-kodeverk-java:9e7b71c1691dfda48f4de4a55fd0b7d6e1b6a241
    steps:
      - run: |
          echo "BACKEND ${BACKEND_VERSION}"
        env:
          BACKEND_VERSION: ${{needs.lag_snapshot_versjon.outputs.backend_versjon}}
