on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  bygge_frontend:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.parse_commit.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: v1-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            v1-yarn-
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - id: parse_commit
        run: |
          echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      - uses: actions/upload-artifact@v1
        with:
          name: melosys-kodeverk
          path: dist

  lag_versjon:
    needs: bygge_frontend
    runs-on: ubuntu-latest
    outputs:
      frontend_versjon: ${{ steps.versjoner.outputs.frontend }}
      backend_versjon: ${{ steps.versjoner.outputs.backend }}
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: melosys-kodeverk
          path: dist
      - id: versjoner
        run: |
          echo "PR_NUMBER ${PR_NUMBER}"
          if [ ${IS_MASTER} == true ]; then
            echo "IS_MASTER"
          else
            echo "NOT IS_MASTER"
          fi
          echo "::set-output name=frontend::$(cat dist/semver.txt)-beta.${SHORT_SHA}"
          echo "::set-output name=backend::$(cat dist/semver.txt)-${SHORT_SHA}-SNAPSHOT"
        env:
          IS_MASTER: ${{ github.ref == 'refs/heads/master' }}
          PR_NUMBER: ${{ github.event.number }}
          SHORT_SHA: ${{needs.bygge_frontend.outputs.short_sha}}
